version: '3.5'

services:
  db_auth:
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
    image: postgres:15.1-bullseye